[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "example_ultralytics_vertex_training"
version = "0.1.0"
description = "train a simple ultralytics model"
authors = [
    { name = "CScott Brown" },
]
dependencies = [
]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
]
